[project]
name = "mlops-pipeline"
version = "0.1.0"
description = "A sample MLOps pipeline project"
requires-python = "~=3.12.11"
dependencies = [
    "mlflow~=2.22.2",
    "pandas~=2.3.3",
    "scikit-learn~=1.7.2",
    "seldon-core~=1.18.2",
]
