[project]
name = "image-classifier"
version = "0.1.0"
description = "A sample image classifier MLOps pipeline project"
requires-python = "~=3.12.11"
dependencies = [
    "Pillow~=11.3.0",
    "seldon-core~=1.18.2",
]
